### ISSUE TITLE
Question about pre-trained weights

### ISSUE THREAD

**Issue by patrickvonplaten** [google-research/bigbird#1]
Thanks so much for releasing BigBird!

Quick question about the pre-trained weights. Do the `bigbr_large` and `bigbr_base` correspond to BERT-like encoder-only checkpoints and `bigbp_large` to the encoder-decoder version?

**Comment by manzilz** [comment]
Yes, you are correct. I should have provided a more detailed documentation.
- `bigbr_large` and `bigbr_base` correspond to BERT/RoBERTa-like encoder only models. Following original BERT and RoBERTa implementation they are transformers with post-normalization, i.e. layer norm is happening after the attention layer. However, following [Rothe et al](https://arxiv.org/abs/1907.12461), we can use them partially in encoder-decoder fashion by coupling the encoder and decoder parameters, as illustrated in [`bigbird/summarization/roberta_base.sh`](https://github.com/google-research/bigbird/blob/master/bigbird/summarization/roberta_base.sh) launch script.
- `bigbp_large` is Pegasus-like encoder-decoder model. Again following original implementation of Pegasus, they are transformers with pre-normalization. They have full set of separate encoder-decoder weights.

**Comment by manzilz** [comment]
I have updated the readme and unless there are further questions I am closing this issue.

**Comment by patrickvonplaten** [comment]
Awesome thanks so much for the quick reply :-)
